modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="contree_des_royaumes"
version="1.0.0.0"
displayName="Contree Des 16 Royaumes"
credits="Mod by Folkers"
displayURL="https://mcreator.net"
authors="Folkers"

[[dependencies.contree_des_royaumes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




